services:
  postgres_db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - ./config/db.env

volumes:
  postgres_db:
    driver: local
  frontend_node_modules:
    driver: local
